### Recuperar todas las planificaciones
GET http://localhost:3333/planning/

### Recuperar por el id de la planificacion
GET http://localhost:3333/planning/653ace2db767888b31dfea59

### Crear una publicacion
POST http://localhost:3333/planning/
Content-Type: application/json

{
    "title": "creado",
    "description": "creado",
    "subscribers": 9,
    "price": 40309,
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "category": "powerlifting", 
    "profesional": {
        "id": "653ab688b767888b31dfea42",
        "name": "Hany",
        "lastname": "Rambod",
        "especialiti": "entrenador"
    }
}

### Eliminar una publicacion
DELETE http://localhost:3333/planning/6542e691e3077efb6c537672

### Actualizar datos de una publicacion
PATCH http://localhost:3333/planning/6542e6cb7f09f34a82a60c4b
Content-Type: application/json

{
    "title": "editado",
    "description": "editado",
    "subscribers": 4,
    "price": 9999,
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "category": "powerlifting", 
    "profesional": {
        "id": "653ab688b767888b31dfea42",
        "name": "Hany",
        "lastname": "Rambod",
        "especialiti": "entrenador"
    }
}