### Recuperar todas las planificaciones
GET http://localhost:3333/planning/

### Filtrar por title
GET http://localhost:3333/planning?title=Programa

### Filtrar por price:
GET http://localhost:3333/planning?pricemin=7000&pricemax=13000

### Filtrar por Category
GET http://localhost:3333/planning?category=running

### Filtrar por subscribers:
GET http://localhost:3333/planning?subscribersmin=5&subscribersmax=9

### Filtrar por especialidad del profesional
GET http://localhost:3333/planning?especialiti=entrenador

### Todos los filtros
http://localhost:3333/planning?title=Programa&pricemin=10000&pricemax=15000&category=powerlifting&subscribersmin=1&subscribersmax=5&especialiti=entrenador

### Recuperar por el id de la planificacion
GET http://localhost:3333/planning/6546ab55f4ff6526b5244304

// Verificar porque se rompe cuando el token no es valido
### Crear una publicacion
POST http://localhost:3333/planning/
Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTUxNTUyNWNmNjhhMjVkNmY0OTdjOGQiLCJlbWFpbCI6ImJhcnRvbG9uaWFicmFoYW1AZ21haWwuY29tIiwiaWF0IjoxNjk5ODQwNDQwfQ.vvXjFGzY-h4_dB6f3sV5G2e-SgC-MXT5g2qWOx11c8g
# Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTUxNTUyNWNmNjhhMjVkNmY0OTdjOGQiLCJlbWFpbCI6ImJhcnRvbG9uaWFicmFoYW1AZ21haWwuY29tIiwiaWF0IjoxNjk5ODQw
Content-Type: application/json

{
    "title": "creado",
    "description": "creado",
    "subscribers": 9,
    "price": 40309,
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "category": "running", 
    "profesional": {
        "id": "653ab688b767888b31dfea42",
        "name": "Hany",
        "lastname": "Rambod",
        "especialiti": "entrenador"
    }
}

### Eliminar una publicacion
POST http://localhost:3333/planning/6542e691e3077efb6c537672
Auth-Token:
Content-Type: application/json

### Actualizar datos de una publicacion
POST http://localhost:3333/planning/6546ab55f4ff6526b5244304
Auth-Token:
Content-Type: application/json

{
    "title": "editado",
    "description": "editado",
    "subscribers": 4,
    "price": 9999,
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "category": "powerlifting", 
    "profesional": {
        "id": "65515599cf68a25d6f497c8f",
        "name": "Hany",
        "lastname": "Rambod",
        "especialiti": "entrenador"
    }
}