### Recuperar todos los profesionales
GET http://localhost:3333/profesional/

// TODO: FILTRAR POR especialidad

### Recuperar por el id del profesional
GET http://localhost:3333/profesional/653ab94db767888b31dfea49

### Crear un profesional
POST http://localhost:3333/profesional/
Content-Type: application/json

{
    "description": "Soy un apasionado nutricionista con años de experiencia en ayudar a las personas a mejorar su salud y bienestar a través de la alimentación. Mi enfoque se basa en el conocimiento científico, la empatía y el apoyo individualizado. Estoy comprometido a ayudar a mis clientes a adoptar hábitos alimenticios saludables y a alcanzar sus metas de salud y nutrición.",
    "synopsis": "Nutricionista apasionado dedicado a mejorar la salud a través de la alimentación. Mi misión es guiar a las personas hacia una vida más saludable, brindando orientación nutricional experta y apoyo constante. Trabajaremos juntos para mejorar tus hábitos alimenticios, superar desafíos y alcanzar tus objetivos de salud y nutrición. ¡Únete a mí y comencemos este viaje hacia un estilo de vida más saludable!",
    "banner": "https://picsum.photos/400/225",
    "alt": "Imagen de nutricionista",
    "subscribers": 4,
    "user": "653ab688b767888b31dfea42",
    "especialidad": "nutricionista"
}

### Eliminar un profesional
DELETE http://localhost:3333/profesional/653ab94db767888b31dfea49

### Actualizar datos de un profesional
PATCH http://localhost:3333/profesional/653d384d66df85561f61ef8b
Content-Type: application/json

{
    "description": "editado",
    "synopsis": "editado",
    "banner": "https://picsum.photos/400/225",
    "alt": "Imagen de nutricionista",
    "subscribers": 4,
    "user": "653ab688b767888b31dfea42",
    "especialidad": "nutricionista"
}