### Recupera todas las categorias de las planificaciones
GET http://localhost:3333/categories/

### Recupera todos los roles de los usuarios
GET http://localhost:3333/roles/

### Recupera todas las especialidades de los entrenadores
GET http://localhost:3333/specialities/
