### Recuperar todos los usuarios
GET http://localhost:3333/users/

### Recuperar por el id del usuario
GET http://localhost:3333/users/65511d7bc14405d4efecedbe

### Crear un usuario
POST http://localhost:3333/users/create
Content-Type: application/json

{
    "name":"Abraham",
    "lastname":"Bartoloni",
    "email": "barto@gmail.com",
    "password":"1234",
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "rol":"profesional"
}

### Eliminar un usuario
POST http://localhost:3333/users/delete/654fe950219c7e15c965145d

### Actualizar datos de un usuario
POST http://localhost:3333/users/update/65511d7bc14405d4efecedbe
Content-Type: application/json

{
    "name":"edit",
    "lastname":"ado",
    "password":"1234",
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "rol":"atleta"
}