### Recuperar todos los usuarios
GET http://localhost:3333/users/

### Recuperar por el id del usuario
GET http://localhost:3333/users/653d7747a72c3c247e1956b1

### Crear un usuario
POST http://localhost:3333/users/
Auth-Token:
Content-Type: application/json

{
    "name":"Hany",
    "lastname":"Rambod",
    "email": "rambodhany@gmail.com",
    "password":"1234",
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "rol":"profesional"
}

### Eliminar un usuario
POST http://localhost:3333/users/655139385b8239fbdbb5c43d
Auth-Token:
Content-Type: application/json

### Actualizar datos de un usuario
POST http://localhost:3333/users/6542ec6a36aadc36e1b94d1c
Auth-Token:
Content-Type: application/json

{
    "name":"edit",
    "lastname":"ado",
    "email": "editado@gmail.com",
    "password":"1234",
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "rol":"atleta"
}