### Recuperar todas las planificaciones
GET http://localhost:3333/api/planning/

### Filtrar por title
GET http://localhost:3333/api/planning?title=Rutina

### Filtrar por price:
GET http://localhost:3333/api/planning?pricemin=100&pricemax=13000

### Filtrar por Category
GET http://localhost:3333/api/planning?category=crossfit

### Filtrar por subscribers:
GET http://localhost:3333/api/planning?subscribersmin=1&subscribersmax=9

### Filtrar por especialidad del profesional
GET http://localhost:3333/api/planning?especialiti=terapeuta

### Todos los filtros
GET http://localhost:3333/api/planning?title=Programa&pricemin=10000&pricemax=15000&category=powerlifting&subscribersmin=1&subscribersmax=5&especialiti=entrenador

### Filtrar por el profesional
GET http://localhost:3333/api/planning?profesional=65513ed62213339133d5b709
//tiene que ser el id del usuario el que se encuentra en user

### Recuperar por el id de la planificacion
GET http://localhost:3333/api/planning/65513ed62213339133d5b709

### Crear una publicacion
POST http://localhost:3333/api/planning/
Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTUxM2VkNjIyMTMzMzkxMzNkNWI3MDkiLCJlbWFpbCI6Im1lc3NpQGdtYWlsLmNvbSIsImlhdCI6MTcwMDM1MTE2Nn0.VF0SnFpsRDngvV7TALaYNZ9XLT7cJKLh2EdI9GChcro
Content-Type: application/json

{
    "title": "prueba10",
    "description": "messi",
    "subscribers": 10,
    "price": 10,
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "category": "running"
}

### Eliminar una publicacion
DELETE http://localhost:3333/api/planning/6554ccab2948b1a9a9ed91d8
Auth-Token:
Content-Type: application/json

### Actualizar datos de una publicacion
PATCH http://localhost:3333/api/planning/65594a508b9fcd2092f05434
Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTUxNTU5OWNmNjhhMjVkNmY0OTdjOGYiLCJlbWFpbCI6InJhbWJvZGhhbnlAZ21haWwuY29tIiwiaWF0IjoxNzAwMzQ4NTIxfQ.c1U3vR_d6so7l2gqDyK6e54_3QJVvpM7qBxkOKlKhns
Content-Type: application/json

{
    "title": "editado",
    "description": "editado",
    "subscribers": 4,
    "price": 9999,
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "category": "powerlifting"
}