### Recuperar todos los profesionales
GET http://localhost:3333/api/profesional/

// TODO: FILTRAR POR especialidad

### Recuperar por el id del profesional
GET http://localhost:3333/api/profesional/65511aaf1b7752ff5ff398f5

### Crear un profesional
POST http://localhost:3333/api/profesional/
Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTUxM2VkNjIyMTMzMzkxMzNkNWI3MDkiLCJlbWFpbCI6Im1lc3NpQGdtYWlsLmNvbSIsImlhdCI6MTcwMDM1MTE2Nn0.VF0SnFpsRDngvV7TALaYNZ9XLT7cJKLh2EdI9GChcro
Content-Type: application/json

{
    "description": "Es messi",
    "synopsis": "entrenador apasionado dedicado a mejorar la salud a través de la alimentación.",
    "banner": "https://picsum.photos/400/225",
    "alt": "Imagen de entrenador",
    "subscribers": 4,
    "user": "65513ed62213339133d5b709",
    "especialiti": "terapeuta"
}

### Eliminar un profesional
DELETE http://localhost:3333/api/profesional/6554f58d52ababff652c75a9
Auth-Token: 
Content-Type: application/json

### Actualizar datos de un profesional
PATCH http://localhost:3333/api/profesional/6554ce572948b1a9a9ed91db
Auth-Token: 
Content-Type: application/json

{
    "description": "editado",
    "synopsis": "editado",
    "banner": "https://picsum.photos/400/225",
    "alt": "Imagen de nutricionista",
    "subscribers": 4,
    "especialiti": "nutricionista"
}