### Recuperar todos los usuarios
GET http://localhost:3333/api/users/

### Recuperar por el id del usuario
GET http://localhost:3333/api/users/653d7747a72c3c247e1956b1

### Crear un usuario
POST http://localhost:3333/api/users/
Content-Type: application/json

{
    "name":"sara",
    "lastname":"sa",
    "email": "sarasa@gmail.com",
    "password":"1234",
    "alt":"descripcion de la imagen",
    "rol":"atleta"
}

### Eliminar un usuario
DELETE http://localhost:3333/api/users/65bab01e771f4db532501f8f
Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTZmNWQ3ZmE4OTI0N2FjNzBkZTRiNDYiLCJlbWFpbCI6InRpYWFtZWxpYUBwcm90b24uY29tIiwiaWF0IjoxNzAxNzk3NzI1fQ.iV1Dz_Gqk_wOjX6ZIwmBMT05iH9ed_n2Fm1WDj56dgg
Content-Type: application/json

### Actualizar datos de un usuario
PATCH http://localhost:3333/api/users/6554cd4e2948b1a9a9ed91d9
Auth-Token: 
Content-Type: application/json

{
    "name":"edit",
    "lastname":"ado",
    "email": "editado@gmail.com",
    "password":"1234",
    "image":"https://picsum.photos/400/225",
    "alt":"descripcion de la imagen",
    "rol":"atleta"
}